# Generated by Django 6.0.2 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_teams',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(null=True),
        ),
    ]
